In [3]:
import numpy as np
import h5py
import pywt

In [3]:
ls ../

28 Jupyter Notebook Tips, Tricks, and Shortcuts for Data Science_files/
28 Jupyter Notebook Tips, Tricks, and Shortcuts for Data Science.html
3D_initial_condition_for_multi_mode.py
alpha_numerator.txt
analysis.py
derivative.ipynb
dissipation_using_FFT.ipynb
dissipation_using_FFT.py
DissRate.h5
diss_rate_in_3D.py
Dq_numerator.txt
eps_from_dns.py
fft_notes/
f_numerator.txt
input_128/
input_32/
measures.h5
mfa_3D.py
mfa_final.py
mfa_w_slope.py
old_codes/
__pycache__/
rough.ipynb
spectrum_Eplus_minus.py
tmp/
turbulence/
useless/
wavelet-leaders/


In [4]:
f = h5py.File("../DissRate.h5", 'r')
data = f['DissRate'][:]

In [5]:
coeffs = pywt.wavedecn(data, 'db1')

In [59]:
coeffs

[array([[[0.00060271]]]),
 {'aad': array([[[-2.60380825e-05]]]),
  'ada': array([[[5.52078522e-06]]]),
  'add': array([[[-7.07611229e-06]]]),
  'daa': array([[[6.68298961e-06]]]),
  'dad': array([[[6.2382569e-06]]]),
  'dda': array([[[6.28211902e-06]]]),
  'ddd': array([[[-4.58843045e-07]]])},
 {'aad': array([[[ 6.75515744e-06, -4.79696691e-06],
          [-4.01144454e-06, -6.15083256e-06]],
  
         [[ 6.61366975e-06, -1.03302718e-06],
          [ 4.08740804e-06,  2.33226139e-05]]]),
  'ada': array([[[ 4.49357425e-07,  1.22717721e-05],
          [ 2.44916526e-06,  1.09456014e-06]],
  
         [[-4.08113405e-06,  5.07515450e-06],
          [-4.49315025e-06, -2.44109103e-06]]]),
  'add': array([[[-1.27210158e-05, -2.92958067e-06],
          [ 7.10078332e-06, -1.29283695e-05]],
  
         [[-8.32469779e-06,  1.48485680e-05],
          [ 1.27241630e-05, -3.74051446e-06]]]),
  'daa': array([[[ 1.16057373e-05,  5.41517365e-06],
          [ 1.89271001e-06,  9.29285336e-06]],
  
        

In [69]:
key_list = list(coeffs[4].keys())
key_list[3]

'daa'

In [72]:
coeffs[2]['aad'].ndim

3

In [75]:
coeffs[3]['aad']

array([[[-7.24540014e-07,  4.83585538e-06,  6.02303912e-06,
         -2.95487899e-06],
        [-6.88022263e-07, -3.12347825e-06, -1.80846561e-05,
         -3.00675208e-06],
        [-4.67772658e-06,  1.20530743e-05,  3.57354291e-06,
         -5.22530463e-06],
        [ 2.94329618e-06, -1.98990590e-06, -3.91065552e-06,
          1.17714843e-05]],

       [[ 8.86881373e-06, -1.78672319e-06, -5.04527823e-06,
         -1.15933368e-05],
        [ 3.86947448e-06,  2.50396325e-06, -2.64845935e-06,
         -1.43337414e-06],
        [ 3.99701860e-06,  7.13819926e-06,  7.06047826e-07,
         -1.72274199e-05],
        [ 5.93000720e-06, -2.57999670e-06,  4.58981997e-07,
         -6.02419558e-06]],

       [[-3.26287674e-06,  3.62597355e-06, -7.80432584e-06,
          5.46523069e-06],
        [-1.28961619e-07,  3.48679240e-06, -7.20988174e-06,
         -1.20209078e-05],
        [ 3.61701259e-06, -6.61981972e-06, -3.39946223e-07,
         -3.42153913e-06],
        [-4.56935993e-06,  7.98527059e-

In [58]:
a = np.array([6,2,7,5])
b = np.array([4,3,5,2,1,0,4,3])
c = np.linspace(0, 15,16)
d = np.linspace(0,31,32)
print(a)
print(b)
print(c)
print(d)
L = [a,b,c, d]
nk = L[0].shape[-1]
nj = len(L)
for k in range(1,nk-1):
    l = []
    for j in range(nj):
        ki = 2**j * (k-1)
        kf = 2**j * (k+2)
        lambda_jk = L[j][ki:kf]
        print(lambda_jk.shape[-1])
        l = l + list(lambda_jk)
    print(max(l))

[6 2 7 5]
[4 3 5 2 1 0 4 3]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31.]
3
6
12
24
23.0
3
6
12
24
31.0


In [6]:
a = np.random.rand(4,4,4)
b = np.random.rand(8,8,8)
c = np.random.rand(16, 16,16)
d = np.random.rand(32,32,32)
# print(a)
# print(b)
# print(c)
# print(d)

In [36]:
def _Lj3D(coeffs, level):
    """
    Determines the LOCAL wavelet leader (i.e. corresponding to the combination of filters
    of which the coefficient list is provided in the argument).
    Parameters
    ----------
    coeffs : list of arrays
        The input list of arrays of the coefficients ordered as [cDn, cDn-1,....,cD1], cDn
        is an array with n being the level.
    level : number
        A non-negative integer number. Higher the level, larger the scale and smaller the number of
        coefficients.
        
    Returns
    ------
    out : list
        The list of local wavelet leaders.
        
    Example
    -------
    a,b,c being the wavelet coefficients generated randomly.
    a = np.random.rand(4,4,4)
    b = np.random.rand(8,8,8)
    c = np.random.rand(16,16,16)
    Coeffs_list = [a,b,c]
    Lj = _Lj3D(Coeffs_list,3)
    len(Lj)
    Ans: 8
    """
    if level > len(coeffs) or level < 0:
        raise ValueError("The value of level is out of range [1, {:d}]".format(len(coeffs)))
    L = coeffs[-level:]
    nkx = L[0].shape[0]
    nky = L[0].shape[1]
    nkz = L[0].shape[2]
    nj = len(L)
    Lj = []
    for kx in range(1,nkx-1):
        for ky in range(1,nky-1):
            for kz in range(1,nkz-1):
                neighborhood = []
                for j in range(nj):
                    kxi = 2**j * (kx-1)
                    kxf = 2**j * (kx+2)
                    kyi = 2**j * (ky-1)
                    kyf = 2**j * (ky+2)
                    kzi = 2**j * (kz-1)
                    kzf = 2**j * (kz+2)
                    lambda_jk = L[j][kxi:kxf, kyi:kyf, kzi:kzf]
    #                 print(lambda_jk.shape)
                    flatten_array = lambda_jk.ravel()
                    neighborhood = neighborhood + list(flatten_array)
    #             print(max(neighborhood))
                Lj.append(max(neighborhood))
    return Lj

In [41]:
C = [1,2,3]
C[-2:]


[2, 3]

In [42]:
C = [a,b,c]
Lj = _Lj3D(C,3)
Lj

[0.9988460118519675,
 0.9992701978988215,
 0.9988460118519675,
 0.9997884745190383,
 0.9988460118519675,
 0.9992701978988215,
 0.9988460118519675,
 0.9997884745190383]

In [19]:
def _keywise_coeffs(levelwise_coeffs):
    """
    This function converts the list of levelwise coefficients into a list of keywise coefficients.
    
    The wavelet coefficients are stored level wise in a list of dictionaries of key-value pair, while
    computing from pywt.wavedecn(). For the computation of wave-leaders, we need to extract the wavelet
    coefficients at each level for a given key. 
    
    Parameter
    --------
    levelwise_coeffs : list of dictionaries
        
    Return
    ------
    out : list of lists
    """
    max_level = len(levelwise_coeffs)
#     print(max_level)
    key_list = list(levelwise_coeffs[1].keys())
#     print(key_list)
    L = []
    for key in key_list:
#         print(key)
        l = []
        for level in range(1,max_level):
            l.append(levelwise_coeffs[level][key])
        L.append(l)
    return L

In [20]:
L = _keywise_coeffs(coeffs)

In [21]:
L[0][2].shape

(4, 4, 4)

In [14]:
def _waveleader(coeffs, level):
    """
    Determines the global wavelet leaders at a given level.
    """
    L = _keywise_coeffs(coeffs)
    

In [15]:
_waveleader(coeffs, 2)

Internal use


In [16]:
a,s = pywt.coeffs_to_array(coeffs)

In [17]:
a.shape

(32, 32, 32)

In [18]:
s

[(slice(None, 1, None), slice(None, 1, None), slice(None, 1, None)),
 {'aad': (slice(None, 1, None), slice(None, 1, None), slice(1, 2, None)),
  'ada': (slice(None, 1, None), slice(1, 2, None), slice(None, 1, None)),
  'add': (slice(None, 1, None), slice(1, 2, None), slice(1, 2, None)),
  'daa': (slice(1, 2, None), slice(None, 1, None), slice(None, 1, None)),
  'dad': (slice(1, 2, None), slice(None, 1, None), slice(1, 2, None)),
  'dda': (slice(1, 2, None), slice(1, 2, None), slice(None, 1, None)),
  'ddd': (slice(1, 2, None), slice(1, 2, None), slice(1, 2, None))},
 {'aad': (slice(None, 2, None), slice(None, 2, None), slice(2, 4, None)),
  'ada': (slice(None, 2, None), slice(2, 4, None), slice(None, 2, None)),
  'add': (slice(None, 2, None), slice(2, 4, None), slice(2, 4, None)),
  'daa': (slice(2, 4, None), slice(None, 2, None), slice(None, 2, None)),
  'dad': (slice(2, 4, None), slice(None, 2, None), slice(2, 4, None)),
  'dda': (slice(2, 4, None), slice(2, 4, None), slice(None, 2, 

In [20]:
a[s[1]['aad']]

array([[[-2.60380825e-05]]])

In [21]:
s[1]['aad']

(slice(None, 1, None), slice(None, 1, None), slice(1, 2, None))

In [22]:
a

array([[[ 6.02706901e-04, -2.60380825e-05,  6.75515744e-06, ...,
          2.01816845e-06,  7.10650525e-08, -3.05362724e-06],
        [ 5.52078522e-06, -7.07611229e-06, -4.01144454e-06, ...,
         -2.07363257e-06,  5.50706606e-07,  1.07518910e-06],
        [ 4.49357425e-07,  1.22717721e-05, -1.27210158e-05, ...,
         -9.39505811e-07,  9.60973825e-07, -2.29005035e-06],
        ...,
        [ 1.40453095e-06,  5.91977919e-06, -2.00050553e-06, ...,
          8.49321175e-06,  6.72014666e-08,  3.40004155e-06],
        [ 1.36294351e-06, -1.09825622e-06,  3.11044426e-06, ...,
         -3.83816376e-06, -2.48768410e-06, -2.04512533e-07],
        [-6.21208535e-06,  4.20600459e-07, -1.16803722e-06, ...,
          1.72001596e-06,  1.26004231e-06,  3.92099439e-06]],

       [[ 6.68298961e-06,  6.23825690e-06,  6.61366975e-06, ...,
         -5.14644757e-06,  1.31845893e-06, -1.26755014e-06],
        [ 6.28211902e-06, -4.58843045e-07,  4.08740804e-06, ...,
         -6.84912855e-06,  2.93591813e

In [23]:
slice(None,1,None)

slice(None, 1, None)